#!/bin/bash

dashless=$(basename "$0" | sed -e 's/-/ /')
OPTIONS_SPEC="$dashless [-b] [-q] [commit]

$dashless looks through the issue's commit message and code for for referenced
issues and opens the configured chili project info for them. Use 'git config
chili.url' to configure the root url.
--
b,browser       open issue in brother
q,quiet         do not display issue description
"

. $(git --exec-path)/git-sh-setup

echo "Options: $*"

quiet=
browser=
xslt="$(dirname $(readlink -f $0))/chili-issue.xsl"

while [ $# -gt 0 ]; do
  opt="$1"
  shift
  case "$opt" in
    -q) quiet=1 ;;
    -b) browser=1 ;;
    --) break ;;
    *)  die-with-status 129 "Unexpected option: $opt" ;;
  esac
done

url=$(git config --get chili.url)

if [ -z "$url" ]
then
  die-with-status 130 "No ChiliProject repository configured. Use something like
  git config chili.url https://projects.gwdg.de/
to configure the repository URL."
fi

# Now try to find something
match_count=0

if [ -z "$quiet" ]
then
  git show -s "$@"
fi

git show -s "$@" | grep -o '#[0-9]\+' | while read bug_ref
do
  bug=${bug_ref:1}
  if [ \! -z "$browser" ]
  then
    git web--browse "${url}/issues/${bug}"
  fi

  if [ -z "$quiet" ]
  then
    curl -s "${url}/issues/${bug}.xml" | xsltproc "${xslt}" -
  fi
done
